import { ApiError } from '@/api/client';

const RO: Record<string, string> = {
  network: 'Nu ne putem conecta la server. Verifică internetul și încearcă din nou.',
  slot_unavailable: 'Ora aleasă tocmai a fost ocupată. Te rugăm alege alta.',
  too_late_to_cancel: 'Programarea nu se mai poate anula din aplicație atât de aproape de oră. Sună-ne, te rog.',
  too_many_active_bookings: 'Ai deja 3 programări viitoare. Anulează una ca să faci alta.',
  too_many_bookings_today: 'Ai făcut multe programări azi. Mai încearcă mâine sau sună la salon.',
  birth_date_locked: 'Data nașterii se poate schimba doar la salon. Spune-ne și o corectăm.',
  assistant_busy: 'Asistentul are foarte multe cereri azi. Încearcă mai târziu sau sună la salon.',
  request_expired: 'Cererea a expirat: ora programării a trecut fără răspuns.',
  request_already_answered: 'Cineva a răspuns deja la această cerere.',
  booking_requested: 'E o cerere încă neconfirmată: întâi o accepți sau o refuzi.',
  slots_available: 'Sunt ore libere în intervalul ales. Alege una și programează-te direct.',
  waitlist_limit: 'Ești deja pe lista de așteptare pentru 5 zile. Scoate o înscriere ca să adaugi alta.',
  waitlist_closed: 'Înscrierea nu mai e pe listă.',
  day_closed: 'Salonul e închis în ziua aceea.',
  day_passed: 'Ziua a trecut deja.',
  invalid_block_kind: 'Alege tipul blocului.',
  block_label_required: 'Pentru „Altceva” scrie și un nume.',
  weekdays_required: 'Alege cel puțin o zi a săptămânii.',
  invalid_range: 'Verifică datele și orele (sfârșitul după început, ore ca 13:00).',
  too_far_ahead: 'Ziua e prea departe. Alege una mai apropiată.',
  wrong_code: 'Codul nu e corect.',
  social_invalid: 'Nu am putut confirma contul. Încearcă din nou sau intră cu telefonul.',
  social_expired: 'A durat prea mult. Apasă din nou pe buton.',
  social_unavailable: 'Logarea cu acest cont nu merge acum. Intră cu telefonul.',
  phone_has_account: 'Numărul are deja cont. Confirmă-l o dată cu codul primit și contul se leagă.',
  code_required: 'Confirmă numărul o dată cu codul primit.',
  code_expired: 'Codul a expirat. Cere unul nou.',
  too_many_attempts: 'Prea multe încercări greșite. Încearcă din nou peste o oră.',
  too_many_requests: 'Ai cerut un cod de curând. Așteaptă puțin și încearcă din nou.',
  sms_code_off: 'Codul se trimite doar pe e-mail. Scrie adresa ta de e-mail.',
  country_not_supported: 'Momentan acceptăm doar numere din România și Europa.',
  invalid_phone: 'Numărul de telefon nu pare corect.',
  invalid_email: 'Adresa de e-mail nu pare corectă.',
  email_in_use: 'Adresa de e-mail e folosită deja de alt cont. Intră cu numărul acelui cont sau scrie altă adresă.',
  email_not_on_account: 'Contul acestui număr nu are încă un e-mail salvat. Primește codul pe SMS, iar e-mailul scris se salvează în cont.',
  email_mismatch: 'E-mailul nu corespunde contului acestui număr. Scrie e-mailul contului sau primește codul pe SMS.',
  wrong_credentials: 'E-mail sau parolă greșită.',
  no_permission: 'Contul tău nu are drept pentru asta. Cere-i proprietarului.',
  range_too_long: 'Perioada e prea lungă. Alege cel mult un an.',
  invalid_tip: 'Bacșișul nu e valid.',
  no_server: 'Partea de echipă merge după ce serverul e online.',
  barber_required: 'Alege frizerul.',
  birth_date_required: 'Scrie data nașterii.',
  invalid_birth_date: 'Data nașterii nu pare corectă. Scrie-o așa: 17.05.1990.',
  email_required: 'Pentru cont nou avem nevoie și de e-mail.',
  too_many_photos: 'Ai deja numărul maxim de poze. Șterge una ca să adaugi alta.',
  image_too_large: 'Poza e prea mare. Încearcă alta.',
  unsupported_image: 'Formatul pozei nu e acceptat. Folosește JPG sau PNG.',
  terms_required: 'Bifează acordul pentru termeni și confidențialitate.',
  unauthorized: 'Sesiunea a expirat. Intră din nou în cont.',
  out_of_stock: 'Unul dintre produse nu mai e pe stoc în cantitatea aleasă. Am actualizat lista, verifică coșul.',
  product_unavailable: 'Unul dintre produse nu mai e disponibil. Am actualizat coșul.',
  too_many_open_orders: 'Ai deja 3 comenzi nepreluate. Ridică-le sau anulează una ca să faci alta.',
  no_active_subscription: 'Clientul nu are un abonament activ (cu tunsori rămase) pentru acest serviciu.',
  already_completed: 'Tunsoarea a fost deja confirmată.',
  booking_cancelled: 'Programarea e anulată și nu se mai poate confirma (ora poate fi deja luată). Fă o programare nouă.',
  plan_not_found: 'Abonamentul nu mai există sau e ascuns.',
  invalid_amount: 'Suma nu e corectă.',
  gift_cards_off: 'Momentan salonul nu vinde carduri cadou din aplicație.',
  too_many_gift_cards: 'Ai deja 5 carduri cadou neplătite. Plătește-le la salon sau anulează unul.',
  not_pending: 'Cardul a fost deja plătit sau anulat.',
  payments_off: 'Plata online nu e pornită încă. Poți plăti la salon.',
  assistant_off: 'Asistentul nu e pornit încă.',
  assistant_failed: 'Asistentul nu a putut răspunde acum. Încearcă din nou.',
  assistant_limit: 'Ai trimis multe mesaje azi. Revino mâine sau sună la salon.',
  audio_too_long: 'Mesajul vocal e prea lung. Încearcă unul mai scurt.',
  payment_failed: 'Nu am putut deschide plata. Încearcă din nou sau plătește la salon.',
  order_paid: 'Comanda e deja plătită. Pentru anulare, sună la salon.',
  not_payable: 'Comanda nu mai poate fi plătită.',
  gift_card_not_found: 'Nu există un card cadou activ cu acest cod.',
  gift_card_expired: 'Cardul cadou a expirat.',
  gift_card_empty: 'Pe cardul cadou nu mai sunt bani.',
  bonus_not_active: 'Bonusul nu mai e activ.',
  not_cancellable: 'Comanda e deja pregătită și nu mai poate fi anulată din aplicație. Sună-ne, te rog.',
};

/** Mesaj pe înțelesul clientului pentru o eroare de la server. */
export function errorMessage(e: unknown, fallback = 'A apărut o problemă. Încearcă din nou.'): string {
  return e instanceof ApiError ? (RO[e.code] ?? fallback) : fallback;
}
