import { ApiError } from '@/api/client';

const RO: Record<string, string> = {
  network: 'Nu ne putem conecta la server. Verifică internetul și încearcă din nou.',
  slot_unavailable: 'Ora aleasă tocmai a fost ocupată. Te rugăm alege alta.',
  too_late_to_cancel: 'Programarea nu se mai poate anula din aplicație atât de aproape de oră. Sună-ne, te rog.',
  too_many_active_bookings: 'Ai deja 3 programări viitoare. Anulează una ca să faci alta.',
  wrong_code: 'Codul nu e corect.',
  code_expired: 'Codul a expirat. Cere unul nou.',
  too_many_attempts: 'Prea multe încercări. Cere un cod nou.',
  too_many_requests: 'Ai cerut un cod de curând. Așteaptă puțin și încearcă din nou.',
  country_not_supported: 'Momentan acceptăm doar numere din România și Europa.',
  invalid_phone: 'Numărul de telefon nu pare corect.',
  invalid_email: 'Adresa de e-mail nu pare corectă.',
  email_not_on_account: 'Contul acestui număr nu are încă un e-mail salvat. Primește codul pe SMS, iar e-mailul scris se salvează în cont.',
  email_mismatch: 'E-mailul nu corespunde contului acestui număr. Scrie e-mailul contului sau primește codul pe SMS.',
  wrong_credentials: 'E-mail sau parolă greșită.',
  no_permission: 'Contul tău nu are drept pentru asta. Cere-i proprietarului.',
  range_too_long: 'Perioada e prea lungă. Alege cel mult un an.',
  invalid_tip: 'Bacșișul nu e valid.',
  no_server: 'Partea de echipă merge după ce serverul e online.',
  barber_required: 'Alege frizerul.',
  birth_date_required: 'Scrie data nașterii.',
  invalid_birth_date: 'Data nașterii nu pare corectă. Scrie-o așa: 17.05.1990.',
  email_required: 'Pentru cont nou avem nevoie și de e-mail.',
  too_many_photos: 'Ai deja numărul maxim de poze. Șterge una ca să adaugi alta.',
  image_too_large: 'Poza e prea mare. Încearcă alta.',
  unsupported_image: 'Formatul pozei nu e acceptat. Folosește JPG sau PNG.',
  terms_required: 'Bifează acordul pentru termeni și confidențialitate.',
  unauthorized: 'Sesiunea a expirat. Intră din nou în cont.',
  out_of_stock: 'Unul dintre produse nu mai e pe stoc în cantitatea aleasă. Am actualizat lista, verifică coșul.',
  product_unavailable: 'Unul dintre produse nu mai e disponibil. Am actualizat coșul.',
  too_many_open_orders: 'Ai deja 3 comenzi nepreluate. Ridică-le sau anulează una ca să faci alta.',
  no_active_subscription: 'Clientul nu are un abonament activ (cu tunsori rămase) pentru acest serviciu.',
  already_completed: 'Tunsoarea a fost deja confirmată.',
  booking_cancelled: 'Programarea e anulată.',
  plan_not_found: 'Abonamentul nu mai există sau e ascuns.',
  invalid_amount: 'Suma nu e corectă.',
  gift_cards_off: 'Momentan salonul nu vinde carduri cadou din aplicație.',
  too_many_gift_cards: 'Ai deja 5 carduri cadou neplătite. Plătește-le la salon sau anulează unul.',
  not_pending: 'Cardul a fost deja plătit sau anulat.',
  payments_off: 'Plata online nu e pornită încă. Poți plăti la salon.',
  payment_failed: 'Nu am putut deschide plata. Încearcă din nou sau plătește la salon.',
  order_paid: 'Comanda e deja plătită. Pentru anulare, sună la salon.',
  not_payable: 'Comanda nu mai poate fi plătită.',
  gift_card_not_found: 'Nu există un card cadou activ cu acest cod.',
  gift_card_expired: 'Cardul cadou a expirat.',
  gift_card_empty: 'Pe cardul cadou nu mai sunt bani.',
  bonus_not_active: 'Bonusul nu mai e activ.',
  not_cancellable: 'Comanda e deja pregătită și nu mai poate fi anulată din aplicație. Sună-ne, te rog.',
};

/** Mesaj pe înțelesul clientului pentru o eroare de la server. */
export function errorMessage(e: unknown, fallback = 'A apărut o problemă. Încearcă din nou.'): string {
  return e instanceof ApiError ? (RO[e.code] ?? fallback) : fallback;
}
